### ISSUE TITLE
Confusion between Physical and Virtual Caches

### ISSUE THREAD

**Issue by sarsanaee** [WukLab/LegoOS#6]
Hi @lastweek 

I was reading your paper with great interest, and I noticed that you have virtual caches there. But the current CPUs are working based on physical caches, right?

This is my understanding:

Conventional System: `Virtual Address -> TLB -> Physical Address -> SRAM Cache -> Memory `

Your System: `Virtual Address -> No Translation on CPU side! -> SRAM Cache -> Excache(DRAM Cache) -> Memory Component`

So how you managed to have a virtual CPU cache? Although the CPU Caches(SRAM) have been designed to work with physical addresses.

Thanks

**Comment by lastweek** [comment]
Hi @sarsanaee,

Using virtual cache is a design choice. But during practice, we use x86 CPU's current architecture to _simulate_ the virtual cache's functionalities such as Miss Handling, Eviction. However, we can't avoid using x86 CPU's current setting such as VIPT L1, physcal L2-L3, and paging. Thus, once ExCache is filled (i.e., x86 pgtable is established) and returned to userspace, the application will just run with physical cache's performance.

A detailed pgfault handling:
- First time page fault, application trap to kernel. Kernel got the faulting virtual address (VA). We then use this VA to _index_ the simulated virtual cache. We found an empty cache line within the mapped cache set, then send requests to mComponent to get the data. After we got the data, we then fill the x86's pgtable to _simulate_ the effect of an successful virtual cache fill. All subsequent accesses just go through the x86's mechanisms to access data.

Related code:
- Where pgfault call ExCache handling: https://github.com/WukLab/LegoOS/blob/master/arch/x86/mm/fault.c#L716
- The entry point of ExCache handling: https://github.com/WukLab/LegoOS/blob/master/managers/processor/pcache/fault.c#L627

**Comment by TongRuizheWithGzz** [comment]
Hi @lastweek ,

I was confused about how you implement ExCache. In your paper, you say "the ExCache hit path is done by hardware", but I thought the hardware cannot manage to locate the ExCache line because ExCache is implemented using normal DRAM. Also, how can your simulate virtual cache by x86 L1~3 cache? I thought the only way is to disable paging... 

Thanks a lot!
------------------------------------------------------------------------------------------------------
I read your wonderful paper carefully again. I thought you did nothing to the current x86 architecture. The ExCache is actually a part of main memory.  Paging, L1~3, TLB work the same. The only difference is that when page fault, Monolithic may seek the page from disk while LegoOS seek the page from mComponent. Am I right~~~?

**Comment by lastweek** [comment]
> Hi @lastweek ,
> 
> I was confused about how you implement ExCache. In your paper, you say "the ExCache hit path is done by hardware", but I thought the hardware cannot manage to locate the ExCache line because ExCache is implemented using normal DRAM. Also, how can your simulate virtual cache by x86 L1~3 cache? I thought the only way is to disable paging...
> 
> ## Thanks a lot!
> I read your wonderful paper carefully again. I thought you did nothing to the current x86 architecture. The ExCache is actually a part of main memory. Paging, L1~3, TLB work the same. The only difference is that when page fault, Monolithic may seek the page from disk while LegoOS seek the page from mComponent. Am I right~~~?

Hi @TongRuizheWithGzz,

Thank you for your kind words. Yes, you are correct. There is nothing we can do to the current x86 architecture. The mechanism difference lies in how pgfault is handled. When pgfault happen in LegoOS, we take in the faulting virtual address, and simulate the behaviors of a virtual cache. After the pgfault has established the pgtable, all following hits are managed by hardware, i.e., VIPT L1, and physical L2-L3.

**Comment by sarsanaee** [comment]
Hello again @lastweek 

Thanks for the answers to the questions, 

![image](https://user-images.githubusercontent.com/3644605/57904568-d4677e00-78a5-11e9-9ec5-25a10623793b.png)

I actually understand the fault handling. However, what cannot digest here is how the hardware manages to translate a virtual address to a cache line in the DRAM on hit path. It is some sort of the same question as @TongRuizheWithGzz asked. Let's assume you get into a cache line in the Excache, how you are doing the tag lookup, for finding the correct way there?

Maybe the difference here would be the way you designed the page tables at different levels that does the tag lookup and finding the cache line index simultaneously.

**Comment by lastweek** [comment]
Hi @sarsanaee,

I think the main confusion here is how the current x86 hardware is able to handle this virtual address to ExCache translation. The short answer is: no, the x86 cannot do as what we described in the text.

At a high-level, the paper describes two things: the design, and the actual implementation. The whole chapter 4 is about design. Some designs are not feasible now, but we think they should be the ideal case in disaggregation architecture. ExCache is one of them. The above text snippet you posted is the ideal design of ExCache we can think of _IF_ there is really an ExCache available.

However, the actual design of ExCache is not possible to deploy on x86, because we cannot hack x86 low-level cache mgmt. That comes back to the second part of the paper: the actual implementation. In the real impl, the miss path is handled by sw to simulate virtual $. But the hit path is still the physical cache path, i.e., the way x86 handles cache.

Hope this helps.

**Comment by sarsanaee** [comment]
Hello

Thanks @lastweek 

Yeah, that helped, so I'm gonna close this issue.

Cheers,
Alireza
